/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios/index'
import { Route as AuthenticatedTabelasPrecosRouteImport } from './routes/_authenticated/tabelas/precos'
import { Route as AuthenticatedTabelasCustosRouteImport } from './routes/_authenticated/tabelas/custos'
import { Route as AuthenticatedRelatoriosPrestadoraRouteImport } from './routes/_authenticated/relatorios/prestadora'
import { Route as AuthenticatedRelatoriosHotelRouteImport } from './routes/_authenticated/relatorios/hotel'
import { Route as AuthenticatedRelatoriosFinanceiroRouteImport } from './routes/_authenticated/relatorios/financeiro'
import { Route as AuthenticatedRelatoriosClienteRouteImport } from './routes/_authenticated/relatorios/cliente'
import { Route as AuthenticatedOperacaoRollPrestadoraRouteImport } from './routes/_authenticated/operacao/roll-prestadora'
import { Route as AuthenticatedOperacaoRollAlyaniRouteImport } from './routes/_authenticated/operacao/roll-alyani'
import { Route as AuthenticatedOperacaoConferenciaRouteImport } from './routes/_authenticated/operacao/conferencia'
import { Route as AuthenticatedFinanceiroPagamentosRouteImport } from './routes/_authenticated/financeiro/pagamentos'
import { Route as AuthenticatedFinanceiroFluxoDeCaixaRouteImport } from './routes/_authenticated/financeiro/fluxo-de-caixa'
import { Route as AuthenticatedFinanceiroCobrancasRouteImport } from './routes/_authenticated/financeiro/cobrancas'
import { Route as AuthenticatedCadastrosPrestadorasRouteImport } from './routes/_authenticated/cadastros/prestadoras'
import { Route as AuthenticatedCadastrosPecasRouteImport } from './routes/_authenticated/cadastros/pecas'
import { Route as AuthenticatedCadastrosHoteisRouteImport } from './routes/_authenticated/cadastros/hoteis'
import { Route as AuthenticatedOperacaoRollPrestadoraIdRouteImport } from './routes/_authenticated/operacao/roll-prestadora.$id'
import { Route as AuthenticatedOperacaoRollAlyaniIdRouteImport } from './routes/_authenticated/operacao/roll-alyani.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTabelasPrecosRoute =
  AuthenticatedTabelasPrecosRouteImport.update({
    id: '/tabelas/precos',
    path: '/tabelas/precos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTabelasCustosRoute =
  AuthenticatedTabelasCustosRouteImport.update({
    id: '/tabelas/custos',
    path: '/tabelas/custos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosPrestadoraRoute =
  AuthenticatedRelatoriosPrestadoraRouteImport.update({
    id: '/relatorios/prestadora',
    path: '/relatorios/prestadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosHotelRoute =
  AuthenticatedRelatoriosHotelRouteImport.update({
    id: '/relatorios/hotel',
    path: '/relatorios/hotel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosFinanceiroRoute =
  AuthenticatedRelatoriosFinanceiroRouteImport.update({
    id: '/relatorios/financeiro',
    path: '/relatorios/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosClienteRoute =
  AuthenticatedRelatoriosClienteRouteImport.update({
    id: '/relatorios/cliente',
    path: '/relatorios/cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRollPrestadoraRoute =
  AuthenticatedOperacaoRollPrestadoraRouteImport.update({
    id: '/operacao/roll-prestadora',
    path: '/operacao/roll-prestadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRollAlyaniRoute =
  AuthenticatedOperacaoRollAlyaniRouteImport.update({
    id: '/operacao/roll-alyani',
    path: '/operacao/roll-alyani',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoConferenciaRoute =
  AuthenticatedOperacaoConferenciaRouteImport.update({
    id: '/operacao/conferencia',
    path: '/operacao/conferencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroPagamentosRoute =
  AuthenticatedFinanceiroPagamentosRouteImport.update({
    id: '/financeiro/pagamentos',
    path: '/financeiro/pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroFluxoDeCaixaRoute =
  AuthenticatedFinanceiroFluxoDeCaixaRouteImport.update({
    id: '/financeiro/fluxo-de-caixa',
    path: '/financeiro/fluxo-de-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCobrancasRoute =
  AuthenticatedFinanceiroCobrancasRouteImport.update({
    id: '/financeiro/cobrancas',
    path: '/financeiro/cobrancas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosPrestadorasRoute =
  AuthenticatedCadastrosPrestadorasRouteImport.update({
    id: '/cadastros/prestadoras',
    path: '/cadastros/prestadoras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosPecasRoute =
  AuthenticatedCadastrosPecasRouteImport.update({
    id: '/cadastros/pecas',
    path: '/cadastros/pecas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosHoteisRoute =
  AuthenticatedCadastrosHoteisRouteImport.update({
    id: '/cadastros/hoteis',
    path: '/cadastros/hoteis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRollPrestadoraIdRoute =
  AuthenticatedOperacaoRollPrestadoraIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOperacaoRollPrestadoraRoute,
  } as any)
const AuthenticatedOperacaoRollAlyaniIdRoute =
  AuthenticatedOperacaoRollAlyaniIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedOperacaoRollAlyaniRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cadastros/hoteis': typeof AuthenticatedCadastrosHoteisRoute
  '/cadastros/pecas': typeof AuthenticatedCadastrosPecasRoute
  '/cadastros/prestadoras': typeof AuthenticatedCadastrosPrestadorasRoute
  '/financeiro/cobrancas': typeof AuthenticatedFinanceiroCobrancasRoute
  '/financeiro/fluxo-de-caixa': typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  '/financeiro/pagamentos': typeof AuthenticatedFinanceiroPagamentosRoute
  '/operacao/conferencia': typeof AuthenticatedOperacaoConferenciaRoute
  '/operacao/roll-alyani': typeof AuthenticatedOperacaoRollAlyaniRouteWithChildren
  '/operacao/roll-prestadora': typeof AuthenticatedOperacaoRollPrestadoraRouteWithChildren
  '/relatorios/cliente': typeof AuthenticatedRelatoriosClienteRoute
  '/relatorios/financeiro': typeof AuthenticatedRelatoriosFinanceiroRoute
  '/relatorios/hotel': typeof AuthenticatedRelatoriosHotelRoute
  '/relatorios/prestadora': typeof AuthenticatedRelatoriosPrestadoraRoute
  '/tabelas/custos': typeof AuthenticatedTabelasCustosRoute
  '/tabelas/precos': typeof AuthenticatedTabelasPrecosRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/operacao/roll-alyani/$id': typeof AuthenticatedOperacaoRollAlyaniIdRoute
  '/operacao/roll-prestadora/$id': typeof AuthenticatedOperacaoRollPrestadoraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cadastros/hoteis': typeof AuthenticatedCadastrosHoteisRoute
  '/cadastros/pecas': typeof AuthenticatedCadastrosPecasRoute
  '/cadastros/prestadoras': typeof AuthenticatedCadastrosPrestadorasRoute
  '/financeiro/cobrancas': typeof AuthenticatedFinanceiroCobrancasRoute
  '/financeiro/fluxo-de-caixa': typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  '/financeiro/pagamentos': typeof AuthenticatedFinanceiroPagamentosRoute
  '/operacao/conferencia': typeof AuthenticatedOperacaoConferenciaRoute
  '/operacao/roll-alyani': typeof AuthenticatedOperacaoRollAlyaniRouteWithChildren
  '/operacao/roll-prestadora': typeof AuthenticatedOperacaoRollPrestadoraRouteWithChildren
  '/relatorios/cliente': typeof AuthenticatedRelatoriosClienteRoute
  '/relatorios/financeiro': typeof AuthenticatedRelatoriosFinanceiroRoute
  '/relatorios/hotel': typeof AuthenticatedRelatoriosHotelRoute
  '/relatorios/prestadora': typeof AuthenticatedRelatoriosPrestadoraRoute
  '/tabelas/custos': typeof AuthenticatedTabelasCustosRoute
  '/tabelas/precos': typeof AuthenticatedTabelasPrecosRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
  '/operacao/roll-alyani/$id': typeof AuthenticatedOperacaoRollAlyaniIdRoute
  '/operacao/roll-prestadora/$id': typeof AuthenticatedOperacaoRollPrestadoraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/cadastros/hoteis': typeof AuthenticatedCadastrosHoteisRoute
  '/_authenticated/cadastros/pecas': typeof AuthenticatedCadastrosPecasRoute
  '/_authenticated/cadastros/prestadoras': typeof AuthenticatedCadastrosPrestadorasRoute
  '/_authenticated/financeiro/cobrancas': typeof AuthenticatedFinanceiroCobrancasRoute
  '/_authenticated/financeiro/fluxo-de-caixa': typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  '/_authenticated/financeiro/pagamentos': typeof AuthenticatedFinanceiroPagamentosRoute
  '/_authenticated/operacao/conferencia': typeof AuthenticatedOperacaoConferenciaRoute
  '/_authenticated/operacao/roll-alyani': typeof AuthenticatedOperacaoRollAlyaniRouteWithChildren
  '/_authenticated/operacao/roll-prestadora': typeof AuthenticatedOperacaoRollPrestadoraRouteWithChildren
  '/_authenticated/relatorios/cliente': typeof AuthenticatedRelatoriosClienteRoute
  '/_authenticated/relatorios/financeiro': typeof AuthenticatedRelatoriosFinanceiroRoute
  '/_authenticated/relatorios/hotel': typeof AuthenticatedRelatoriosHotelRoute
  '/_authenticated/relatorios/prestadora': typeof AuthenticatedRelatoriosPrestadoraRoute
  '/_authenticated/tabelas/custos': typeof AuthenticatedTabelasCustosRoute
  '/_authenticated/tabelas/precos': typeof AuthenticatedTabelasPrecosRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
  '/_authenticated/operacao/roll-alyani/$id': typeof AuthenticatedOperacaoRollAlyaniIdRoute
  '/_authenticated/operacao/roll-prestadora/$id': typeof AuthenticatedOperacaoRollPrestadoraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/cadastros/hoteis'
    | '/cadastros/pecas'
    | '/cadastros/prestadoras'
    | '/financeiro/cobrancas'
    | '/financeiro/fluxo-de-caixa'
    | '/financeiro/pagamentos'
    | '/operacao/conferencia'
    | '/operacao/roll-alyani'
    | '/operacao/roll-prestadora'
    | '/relatorios/cliente'
    | '/relatorios/financeiro'
    | '/relatorios/hotel'
    | '/relatorios/prestadora'
    | '/tabelas/custos'
    | '/tabelas/precos'
    | '/relatorios/'
    | '/operacao/roll-alyani/$id'
    | '/operacao/roll-prestadora/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/cadastros/hoteis'
    | '/cadastros/pecas'
    | '/cadastros/prestadoras'
    | '/financeiro/cobrancas'
    | '/financeiro/fluxo-de-caixa'
    | '/financeiro/pagamentos'
    | '/operacao/conferencia'
    | '/operacao/roll-alyani'
    | '/operacao/roll-prestadora'
    | '/relatorios/cliente'
    | '/relatorios/financeiro'
    | '/relatorios/hotel'
    | '/relatorios/prestadora'
    | '/tabelas/custos'
    | '/tabelas/precos'
    | '/relatorios'
    | '/operacao/roll-alyani/$id'
    | '/operacao/roll-prestadora/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/cadastros/hoteis'
    | '/_authenticated/cadastros/pecas'
    | '/_authenticated/cadastros/prestadoras'
    | '/_authenticated/financeiro/cobrancas'
    | '/_authenticated/financeiro/fluxo-de-caixa'
    | '/_authenticated/financeiro/pagamentos'
    | '/_authenticated/operacao/conferencia'
    | '/_authenticated/operacao/roll-alyani'
    | '/_authenticated/operacao/roll-prestadora'
    | '/_authenticated/relatorios/cliente'
    | '/_authenticated/relatorios/financeiro'
    | '/_authenticated/relatorios/hotel'
    | '/_authenticated/relatorios/prestadora'
    | '/_authenticated/tabelas/custos'
    | '/_authenticated/tabelas/precos'
    | '/_authenticated/relatorios/'
    | '/_authenticated/operacao/roll-alyani/$id'
    | '/_authenticated/operacao/roll-prestadora/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabelas/precos': {
      id: '/_authenticated/tabelas/precos'
      path: '/tabelas/precos'
      fullPath: '/tabelas/precos'
      preLoaderRoute: typeof AuthenticatedTabelasPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tabelas/custos': {
      id: '/_authenticated/tabelas/custos'
      path: '/tabelas/custos'
      fullPath: '/tabelas/custos'
      preLoaderRoute: typeof AuthenticatedTabelasCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/prestadora': {
      id: '/_authenticated/relatorios/prestadora'
      path: '/relatorios/prestadora'
      fullPath: '/relatorios/prestadora'
      preLoaderRoute: typeof AuthenticatedRelatoriosPrestadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/hotel': {
      id: '/_authenticated/relatorios/hotel'
      path: '/relatorios/hotel'
      fullPath: '/relatorios/hotel'
      preLoaderRoute: typeof AuthenticatedRelatoriosHotelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/financeiro': {
      id: '/_authenticated/relatorios/financeiro'
      path: '/relatorios/financeiro'
      fullPath: '/relatorios/financeiro'
      preLoaderRoute: typeof AuthenticatedRelatoriosFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/cliente': {
      id: '/_authenticated/relatorios/cliente'
      path: '/relatorios/cliente'
      fullPath: '/relatorios/cliente'
      preLoaderRoute: typeof AuthenticatedRelatoriosClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/roll-prestadora': {
      id: '/_authenticated/operacao/roll-prestadora'
      path: '/operacao/roll-prestadora'
      fullPath: '/operacao/roll-prestadora'
      preLoaderRoute: typeof AuthenticatedOperacaoRollPrestadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/roll-alyani': {
      id: '/_authenticated/operacao/roll-alyani'
      path: '/operacao/roll-alyani'
      fullPath: '/operacao/roll-alyani'
      preLoaderRoute: typeof AuthenticatedOperacaoRollAlyaniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/conferencia': {
      id: '/_authenticated/operacao/conferencia'
      path: '/operacao/conferencia'
      fullPath: '/operacao/conferencia'
      preLoaderRoute: typeof AuthenticatedOperacaoConferenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/pagamentos': {
      id: '/_authenticated/financeiro/pagamentos'
      path: '/financeiro/pagamentos'
      fullPath: '/financeiro/pagamentos'
      preLoaderRoute: typeof AuthenticatedFinanceiroPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/fluxo-de-caixa': {
      id: '/_authenticated/financeiro/fluxo-de-caixa'
      path: '/financeiro/fluxo-de-caixa'
      fullPath: '/financeiro/fluxo-de-caixa'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoDeCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/cobrancas': {
      id: '/_authenticated/financeiro/cobrancas'
      path: '/financeiro/cobrancas'
      fullPath: '/financeiro/cobrancas'
      preLoaderRoute: typeof AuthenticatedFinanceiroCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/prestadoras': {
      id: '/_authenticated/cadastros/prestadoras'
      path: '/cadastros/prestadoras'
      fullPath: '/cadastros/prestadoras'
      preLoaderRoute: typeof AuthenticatedCadastrosPrestadorasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/pecas': {
      id: '/_authenticated/cadastros/pecas'
      path: '/cadastros/pecas'
      fullPath: '/cadastros/pecas'
      preLoaderRoute: typeof AuthenticatedCadastrosPecasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/hoteis': {
      id: '/_authenticated/cadastros/hoteis'
      path: '/cadastros/hoteis'
      fullPath: '/cadastros/hoteis'
      preLoaderRoute: typeof AuthenticatedCadastrosHoteisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao/roll-prestadora/$id': {
      id: '/_authenticated/operacao/roll-prestadora/$id'
      path: '/$id'
      fullPath: '/operacao/roll-prestadora/$id'
      preLoaderRoute: typeof AuthenticatedOperacaoRollPrestadoraIdRouteImport
      parentRoute: typeof AuthenticatedOperacaoRollPrestadoraRoute
    }
    '/_authenticated/operacao/roll-alyani/$id': {
      id: '/_authenticated/operacao/roll-alyani/$id'
      path: '/$id'
      fullPath: '/operacao/roll-alyani/$id'
      preLoaderRoute: typeof AuthenticatedOperacaoRollAlyaniIdRouteImport
      parentRoute: typeof AuthenticatedOperacaoRollAlyaniRoute
    }
  }
}

interface AuthenticatedOperacaoRollAlyaniRouteChildren {
  AuthenticatedOperacaoRollAlyaniIdRoute: typeof AuthenticatedOperacaoRollAlyaniIdRoute
}

const AuthenticatedOperacaoRollAlyaniRouteChildren: AuthenticatedOperacaoRollAlyaniRouteChildren =
  {
    AuthenticatedOperacaoRollAlyaniIdRoute:
      AuthenticatedOperacaoRollAlyaniIdRoute,
  }

const AuthenticatedOperacaoRollAlyaniRouteWithChildren =
  AuthenticatedOperacaoRollAlyaniRoute._addFileChildren(
    AuthenticatedOperacaoRollAlyaniRouteChildren,
  )

interface AuthenticatedOperacaoRollPrestadoraRouteChildren {
  AuthenticatedOperacaoRollPrestadoraIdRoute: typeof AuthenticatedOperacaoRollPrestadoraIdRoute
}

const AuthenticatedOperacaoRollPrestadoraRouteChildren: AuthenticatedOperacaoRollPrestadoraRouteChildren =
  {
    AuthenticatedOperacaoRollPrestadoraIdRoute:
      AuthenticatedOperacaoRollPrestadoraIdRoute,
  }

const AuthenticatedOperacaoRollPrestadoraRouteWithChildren =
  AuthenticatedOperacaoRollPrestadoraRoute._addFileChildren(
    AuthenticatedOperacaoRollPrestadoraRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCadastrosHoteisRoute: typeof AuthenticatedCadastrosHoteisRoute
  AuthenticatedCadastrosPecasRoute: typeof AuthenticatedCadastrosPecasRoute
  AuthenticatedCadastrosPrestadorasRoute: typeof AuthenticatedCadastrosPrestadorasRoute
  AuthenticatedFinanceiroCobrancasRoute: typeof AuthenticatedFinanceiroCobrancasRoute
  AuthenticatedFinanceiroFluxoDeCaixaRoute: typeof AuthenticatedFinanceiroFluxoDeCaixaRoute
  AuthenticatedFinanceiroPagamentosRoute: typeof AuthenticatedFinanceiroPagamentosRoute
  AuthenticatedOperacaoConferenciaRoute: typeof AuthenticatedOperacaoConferenciaRoute
  AuthenticatedOperacaoRollAlyaniRoute: typeof AuthenticatedOperacaoRollAlyaniRouteWithChildren
  AuthenticatedOperacaoRollPrestadoraRoute: typeof AuthenticatedOperacaoRollPrestadoraRouteWithChildren
  AuthenticatedRelatoriosClienteRoute: typeof AuthenticatedRelatoriosClienteRoute
  AuthenticatedRelatoriosFinanceiroRoute: typeof AuthenticatedRelatoriosFinanceiroRoute
  AuthenticatedRelatoriosHotelRoute: typeof AuthenticatedRelatoriosHotelRoute
  AuthenticatedRelatoriosPrestadoraRoute: typeof AuthenticatedRelatoriosPrestadoraRoute
  AuthenticatedTabelasCustosRoute: typeof AuthenticatedTabelasCustosRoute
  AuthenticatedTabelasPrecosRoute: typeof AuthenticatedTabelasPrecosRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCadastrosHoteisRoute: AuthenticatedCadastrosHoteisRoute,
  AuthenticatedCadastrosPecasRoute: AuthenticatedCadastrosPecasRoute,
  AuthenticatedCadastrosPrestadorasRoute:
    AuthenticatedCadastrosPrestadorasRoute,
  AuthenticatedFinanceiroCobrancasRoute: AuthenticatedFinanceiroCobrancasRoute,
  AuthenticatedFinanceiroFluxoDeCaixaRoute:
    AuthenticatedFinanceiroFluxoDeCaixaRoute,
  AuthenticatedFinanceiroPagamentosRoute:
    AuthenticatedFinanceiroPagamentosRoute,
  AuthenticatedOperacaoConferenciaRoute: AuthenticatedOperacaoConferenciaRoute,
  AuthenticatedOperacaoRollAlyaniRoute:
    AuthenticatedOperacaoRollAlyaniRouteWithChildren,
  AuthenticatedOperacaoRollPrestadoraRoute:
    AuthenticatedOperacaoRollPrestadoraRouteWithChildren,
  AuthenticatedRelatoriosClienteRoute: AuthenticatedRelatoriosClienteRoute,
  AuthenticatedRelatoriosFinanceiroRoute:
    AuthenticatedRelatoriosFinanceiroRoute,
  AuthenticatedRelatoriosHotelRoute: AuthenticatedRelatoriosHotelRoute,
  AuthenticatedRelatoriosPrestadoraRoute:
    AuthenticatedRelatoriosPrestadoraRoute,
  AuthenticatedTabelasCustosRoute: AuthenticatedTabelasCustosRoute,
  AuthenticatedTabelasPrecosRoute: AuthenticatedTabelasPrecosRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
